status = [
  # Hydra: Aggregate job from release.nix
  "ci/hydra:Bcc:bcc-explorer-app:required"
]
timeout_sec = 7200
required_approvals = 1
cut_body_after = "## Type of change"
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
